# Generated by Django 5.0.1 on 2024-01-29 20:42

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('content', models.TextField(default='')),
                ('category', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='news_images/')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='category', unique=True)),
            ],
            options={
                'verbose_name': 'Spor',
                'verbose_name_plural': 'Sporlar',
            },
        ),
    ]
