# Generated by Django 5.0.1 on 2024-01-29 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_sport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sport',
            options={'verbose_name': 'Spor', 'verbose_name_plural': 'Spor'},
        ),
    ]
