# Generated by Django 5.0.1 on 2024-02-01 08:09

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_sport_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Economy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='news_images/')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='economy', unique=True)),
            ],
            options={
                'verbose_name': 'Ekonomi',
            },
        ),
    ]
