# Generated by Django 5.0.1 on 2024-02-01 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_economy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='economy',
            options={'verbose_name': 'Ekonomi', 'verbose_name_plural': 'Ekonomi'},
        ),
    ]
