# Generated by Django 5.0.1 on 2024-02-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('urgency', models.CharField(choices=[('Low', 'Düşük'), ('Medium', 'Orta'), ('High', 'Yüksek')], max_length=20, verbose_name='Aciliyet')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('agree_to_terms', models.BooleanField(default=False, verbose_name="Kullanım Koşulları'nı Kabul Ediyorum")),
            ],
            options={
                'verbose_name': 'Mesaj',
                'verbose_name_plural': 'İletişim Mesajları',
            },
        ),
    ]
